name: helloworld
description: A new Flutter project.
publish_to: 'none'

version: "1.2.0"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  hugeicons: ^0.0.11
  meta: ^1.16.0
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
          weight: 300
  