name: jvadmin
description: jvadmin app
publish_to: 'none'

version: "1.3.0"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  hugeicons: ^0.0.11
  meta: ^1.16.0
  go_router: ^16.0.0
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Questrial
      fonts:
        - asset: assets/fonts/questrial.ttf
          weight: 300
  